rsocket/rsocket

Protocol.md

I propose to rename METADATA into METADATA_PUSH.
It makes the meaning of the message more obvious.
Also, I added a paragraph to specify the processing order of METADATA_PUSH wrt. RESPONSE.
This specification allows us to implement in the future thing like Shared Dictionary Compression (e.g. SDCH).

Rename METADATA to METADATA_PUSH + specify the processing order

---

Protocol.md

In this pull request, I propose to define three categories of SETUP_ERROR: Invalid, Unsupported and Rejected.
- Invalid correspond to any message that the server can't read or understand, this should be the response that you receive if you send random data.
- Unsupported correspond to a message containing parameters that are unsupported by the server (e.g. encoding, or future capabilities)
- Rejected correspond to an decision made by the server to reject the message (e.g. the server is slowly starting or is overcapacity)

Specify SETUP_ERROR responses

---

Protocol.md

Seeking to add the REQUEST_CHANNEL type: https://github.com/ReactiveSocket/reactivesocket/issues/30
What if we push back REQUEST_N and CANCEL to 20/21, the Response section to 30+, Metadata to 40+ so that we have a gap for a few more interaction models (16-19) if we come up with any more?
This allows putting REQUEST_CHANNEL as 0x0015 alongside the others.

REQUEST_CHANNEL Type

---

Protocol.md

Now that we downgraded the size of the keepalive period field to 32bits, it would be better to also change the time unit to millisecond.
It also adds more conformity, because the unit used in the LEASE frame is also millisecond.

Update keepalive time unit to millisecond

---

Motivations.md
Protocol.md

Issue #69: clarify null terminations are optional.
Issue #67: clarify that handshake overhead is avoided, and not that some existing handshakes are eliminated.

Doc changes for null terminated strings and avoiding handshakes.

---

Protocol.md

While I am implementing some of the js side of things I noticed that some of the definitions appear in different ordering than the frame itself.  This is a simple fix for the ones i have noticed.

switching the order of the definition for the frame to match the frame order

---

FAQ.md

In reading through the FAQ, there were a lot of little typos and bits of sloppy style that eventually totaled up to distracting me from the content. So I just went from the top and pedantically fixed whatever stood out to me, hoping it'll help future readers. There could probably be subjective improvements to wordings, but I mostly tried to avoid those and stick to grammar, syntax, and consistency improvements (a few subjective changes nevertheless crept in…).
GitHub's "rich" prose diff is helpful :smile:

Clean up lots of typos and grammar in FAQ

---

Protocol.md

reword the frame length requirements, to allow for protocol with incompatible framing.
For example HTTP/2 has a negotiated SETTINGS_MAX_FRAME_SIZE, so may be running with frames restricted to 16kb. So a transports such as this must fallback to the stream approach.

US Typo and reword the frame length requirements

---

Protocol.md

Frame Header Format says stream id must be present, but the spec also says Metadata for a request or response should be in the existing Frame.  So this should be a must.

Metadata Push must be for the connection (stream id 0)

---

FAQ.md
Motivations.md
Protocol.md

As discussed in #111, this change removes request-subscription interaction model from the protocol.
**Frame type values have changed.** I did not want to leave a hole in the frame type flags, so I changed the flags specified after `request-subscription`. Yays/Nays?

Fixes Issue #111

---

FAQ.md
Motivations.md
Protocol.md

- Pull out framing into own section. 
- Move StreamID to start RS Header.
- Reduce size of frame length, frame type, flags, and metadata length.
- Remove REQUEST_SUB. 
- Add resume fields to SETUP and KEEPALIVE.
NOTE: Additional frame types for RESUME and RESUME_OK will be in separate PR that details the rest of resuming operation. The fields and frame types are mentioned here for completeness when resume is not used.

Changes for layout and proposed 1.0 changes.

---

Protocol.md

Changing to Motivations, which more-or-less replaced the original Design Goals doc long ago.

Fix Broken Link to Design Goals

---

Protocol.md

The current version of Protocol.md states this:
> ReactiveSocket as specified here only allows for TCP, WebSocket, and Aeron as transport protocols.
Then in the next section, a couple paragraph away it mentions HTTP/2 as needing frame length.
It is confusing to say the protocol only supports TCP, WebSocket, and Aeron, and then mention "HTTP/2" and "Other" in the framing section. 
In this change I propose a possible wording to resolve the confusion. But I'm not quite sure what was meant by this sentence, when the section itself is also permitting other transports. 
So what is trying to be said, and what can we do to make this clearer?

Supported Transports

---

Motivations.md
Protocol.md

Currently, the format of the request N is ambiguous, and the allowed ranges are not specified. This causes problems with cross platform streams and subscriptions.

Add additional spec for 'request N' format

---

Protocol.md

Adding text as suggested by @tmontgomery that permits an implementation to move management of streamId to the underlying transport.

Permit Transport Protocols Managing StreamId

---

Protocol.md

From the HTTP/2 Spec
Streams are identified with an unsigned 31-bit integer.  Streams
initiated by a client MUST use odd-numbered stream identifiers; those
initiated by the server MUST use even-numbered stream identifiers.  A
stream identifier of zero (0x0) is used for connection control
messages; the stream identifier of zero cannot be used to establish a
new stream.

correct stream id logic

---

Protocol.md

As per discussion in https://github.com/ReactiveSocket/reactivesocket/issues/126 in order to remove ambiguity and use of sentinel value of 0-bytes, and allow 0-byte payloads.

Add RESPONSE Next Flag

---

Protocol.md

Support up to 2^16 bytes length for token

Make Resume Identification Token Variable Length

---

Protocol.md

This makes the behavior for resume token similar to metadata. If the flag is not set, then the bytes will not exist in the payload.
This is discussed in https://github.com/ReactiveSocket/reactivesocket/issues/149

Make Resume Token Not Present If Flag Not Set

---

Protocol.md

Rename RESPONSE to PAYLOAD since it flows both directions, not just in response to a request. 
Preparative change for making requestChannel send messages with PAYLOAD, not multiple REQUEST_CHANNEL frames.
Related to discussion in https://github.com/ReactiveSocket/reactivesocket/issues/150

Rename RESPONSE to PAYLOAD

---

Protocol.md

As discussed in issue #59 having an error code to indicate "safe closure" similar to GO_AWAY frame in HTTP/2 will be useful to indicate graceful shutdown as opposed to a fatal error.

`CONNECTION_CLOSE` error code

---

Protocol.md

Adding version in SETUP frame as we realized while implementing v1.0 spec changes that we don't know what version of frames are coming in when we receive a SETUP frame.

Version in RESUME Frame

---

Protocol.md

Lighten up some language to not require retransmit of frames during resumption. From comments in #156

lighten up language around using RESUME frame positions.

---

Protocol.md

Based on feedback of people reading spec for first time, changing section names to match the frame names, and putting in the specific "Frame Type" information for each frame with their hex value.

Match Frame Sections to Frame Names

---

Protocol.md

#160 changed headers text, which broke the "SETUP Frame" and "KEEPALIVE Frame" links.
This PR adds invisible anchors to those headers, which fixes the links and make them less fragile to text changes.
I searched also for links to the other headers that were changed in #160, but couldn't find any.

Fix "SETUP Frame" and "KEEPALIVE Frame" links

---

FAQ.md
MimeTypes.md
Motivations.md
Protocol.md

It would be nice if we always referred to ReactiveSocket as
"ReactiveSocket", and not "ReactiveSockets" or "Reactive Socket".
This PR simply fixes this inconsistency.

Replace "ReactiveSockets" and "Reactive Socket" with "ReactiveSocket"

---

Protocol.md

This makes it consistent with what the frame header section mentions.
cc @benjchristensen

Put (M)etdata present flag before Resume enabled

---

Protocol.md

This means the position of the Complete flag matches other frames which reduces confusion when implementing the spec.
cc @benjchristensen

Swap Complete and Next flags for PAYLOAD

---

Protocol.md

Since there is no `M` in the Frame Contents visualization, I suggest we don't mention it at all.

Remove M flag from KEEPALIVE Frame

---

Motivations.md
Protocol.md
README.md

Similarly to #162, it would be nice to refer to Reactive Streams **always** as "Reactive Streams".

Standardize the name "Reactive Streams"

---

Protocol.md

I suggest removal of this line. In practice no implementation does this, nor have I actually found this be usable, as every usage defines the mimetype in the client/server negotiation. Right now this rule means none of the implementations are actually compliant, and it requires dependency on CBOR since the default format is defined as: application/x.reactivesocket.meta+cbor

remove default metadata encoding

---

Protocol.md

Since HTTP/2 is referenced later, and we target it, I'm calling it out in the transport section, but being specific to it being HTTP/2 streams that we target, as most HTTP/2 clients don't expose stream APIs.

clarify HTTP/2 stream as transport with link

---

Protocol.md

Based on feedback, adopting the style of description used by HTTP/2 (http://httpwg.org/specs/rfc7540.html#FrameHeader) and specifically showing the first bit of 32-bit and 64-bit numbers to always be 0.

Use unsigned for all bit descriptions

---

Protocol.md

Require implementations to send Metadata before Data when fragmented. 
Proposed for https://github.com/ReactiveSocket/reactivesocket/issues/170

Metadata before Data when fragmented

---

Protocol.md

In practice we don't call it NEXT. We call it PAYLOAD.

Remove reference to NEXT naming

---

Protocol.md

Improving the sequence and lifetime docs for channel, and somewhat stream.
Specifically this clarifies that COMPLETE is needed in both directions for channel, and how it behaves with ERROR and CANCEL.

clarify lifetimes, particularly channel

---

Protocol.md

Clarify that the extra bits are to be ignored if the frame doesn't specify them.

Ignore flag bits if not specified for a frame.

---

Protocol.md

It is confusing and doesn't match terminology used elsewhere.
The CLOSED state is not used anywhere else, nor is REQUESTED state. 
This is related to https://github.com/ReactiveSocket/reactivesocket/issues/193 which sought clarification of this section.

remove Stream State section

---

Protocol.md

Clarify language about COMPLETE in the frames with (C)omplete, and in the terminology section.

Clarify COMPLETE

---

Protocol.md

We now have codes up to 204, so application needs to start at 205.

Change application reserved error code range

---

Protocol.md

Solve SETUP_ERROR confusion: https://github.com/ReactiveSocket/reactivesocket/issues/191
Exactly specify what error codes are applicable any time an ERROR frame is referenced.

Specify exact error codes

---

Protocol.md

Unless we determine a reason to keep it, removing so it's not ambiguous: https://github.com/ReactiveSocket/reactivesocket/issues/209

remove (S)trict flag on SETUP

---

Protocol.md

As per discussion in https://github.com/ReactiveSocket/reactivesocket/issues/201, remove Metadata from ERROR, LEASE, and CANCEL frames.

Remove Metadata from CANCEL & ERROR

---

Protocol.md

Mentioning "max value" doesn't make sense when the field value cannot change.

Remove 'max value' when field value is fixed

---

Extensions/Well-Known-MIME-Types.md
README.md

This change adds an extension for well-known MIME types that maps the types to integer values for optimized inclusion in payloads.
> MIME types are an integral part of the RSocket and Extension specifications.  However, due to their definitions as strings and the number of times they need to be sent as part of typical interaction, they can be wasteful in their typical form.  Because of this, it's useful to represent well-known MIME types as integer values during transmission.  This behavior does not remove the need or ability in the specifications to declare MIME types as strings.

Well-known MIME Types

---

Extensions/CompositeMetadata.md
Extensions/Well-Known-MIME-Types.md
README.md

This change adds an extension specific for composite metadata that allows discrete metadata types to be included in a single metadata payload.
> There are a number of situations where an arbitrary collection of discrete metadata types should be attached to frame. For example, a request frame may want to include both routing metadata as well as tracing metadata. This extension specification provides an interoperable structure for metadadata payloads to contain multiple discrete metadata types. It is designed such that if a consumer of the metadata is unaware of a particular type, it can be safely skipped and the next one read.

Composite Metadata Extension Spec

---

Extensions/Tracing-Zipkin.md
Extensions/Well-Known-MIME-Types.md
README.md

This change adds an extension specification for distributed tracing in the Zipkin format.
> Observability and tracing are key requirements for robust and reliable applications.  When using distributed applications connected with RSocket, it's important to propagate metadata about the current logical operations throughout the entire system.  One of the most popular systems for doing this kind of tracing is [Zipkin][z].  This extension specification provides an interoperatble structure for Zipkin metadata payloads to contain tracing information.  It is designed such that systems can efficently communicate span and trace information to a Zipkin server and propagate that information throughout a distributed system.
[z]: https://zipkin.io

Tracing (Zipkin)

---

Extensions/Tracing-Zipkin.md

Previously the extension specification assumed that all trace ids would be 128-bit values.  In the discussion of #256 it was highlighted that not only was this variable between 64-bit and 128-bit, but the primary behavior is 64-bit values.  This change updates the specification to add a new T flag that indicates whether the value is a 64-bit value (unset) or a 128-bit value (set).  This removes the need to pad 64-bit values and ensures the efficiency in the data structure.

64-bit Trace Id

---

Extensions/CompositeMetadata.md
Extensions/Routing.md
Extensions/WellKnownMimeTypes.md
README.md

This change adds an extension specification for routing that allows arbitrary
tags to be included by the requestor for the responder to use for message
routing.
> When two system are communicating via RSocket, there are often logical divisions in the messages that are sent from the requestor to the responder.  These logical divisions can often be implemenated by the responder as "routes" for messages to be sent to.  This extension specification provides an interoperable structure for metadata payloads to contain routing information.  It is designed such that an arbitrary collection of tags can be used by the responder to route messages and any individual tag (or all included tags) can be ignored.

Routing Extension Spec

---

Protocol.md

Clarify that position is byte-count of frames received, including fragmented frames.

clear up resumption tracking

---

Protocol.md

This PR provides an update to the spec, which mentions a Recommendation for all implementations. Basically, it adds a note on prioritized delivering of all the *Stream ID 0* frames in case it is possible.
For example, in RSocket-Java, we have a [Queue](https://github.com/rsocket/rsocket-java/blob/develop/rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java), which basically enqueues all the frames on the Requester level first, and the underlying duplex connection drains them and delivers later on. It means that the KeepAlive frame as an important one could be [stacked](https://github.com/rsocket/rsocket-java/pull/718) in that `Queue` and delayed in its delivery to the connection and subsequently to the Responder.
Undelivered on time KeepAlive frame could cause unwanted …

Provides addition to QoS and Prioritisation

---

Extensions/Security/Simple.md

Looks like it either type in frame representation or frame description :
1) Frame says 8 bits (from 0 bit to 7 bit) where 
2) The description says 7 bits
From my point of view, there is no sense to limit Username length to 128 bits, so it should be fine to have 8 bits for the Username length field

Fixes bit length in Simple Auth payload

---

Extensions/WellKnownMimeTypes.md

Cap’n Proto and FlatBuffers  are high performance serialization library, and they should be included in WellKnownType, and especially useful to per stream DataMimeType, and text MimeType is too long for them because of performance.

adds Cap’n Proto and FlatBuffers to WellKnownMimeTypes
