rsocket/rsocket

- Protocol.md
1. Change layout of Frame Type and flags
1. Use version only for SETUP
1. Make Stream ID 32-bit
1. Make Request N value 32-bit
1. Remove SETUP_ERROR frame and incorporate into ERROR frame
1. Bring in error codes from @stevegury in #63 
1. Add some clarifying language in various places.
> Incorporation of feedback

- Motivations.md
I rearranged some things added some introductory type paragraphs, reworded some things and added some prompts for more examples etc. I think this helps answer why in a lot clearer fashion (at least for the uninitiated).
> filling in the framework

- Protocol.md
We dropped request/subscription, so down from five to four.
> Only Four Types

- Protocol.md
Attempting to be very clear and precise, to the point of pedantic, so there are no questions or misinterpretations as people read the spec.
> Detailed and Consistent Bits/Max Size

- Protocol.md
Add clarity about request(n) being cumulative.
> clarify request(n) being cumulative

- Protocol.md
- moved into SETUP where the value is
- include server-to-server and mobile-to-server commentary
> KEEPALIVE timing suggestions

- Protocol.md
Revision of how request fragmentation will be done with PAYLOAD frames as per discussion in https://github.com/ReactiveSocket/reactivesocket/issues/198
> Request Fragmentation

- Protocol.md
Proposed solution to https://github.com/ReactiveSocket/reactivesocket/issues/210
> remove unclear statement about ignore bit

- Protocol.md
Replacing the dangling reference to LEASE_ERROR and replacing with REJECTED
> LEASE_ERROR -> REJECTED

- Protocol.md
Clarification derived from discussion in https://github.com/ReactiveSocket/reactivesocket/issues/208
> stream id generation

- Protocol.md
Include CANCELED in details throughout doc. Clarify wording on error description.
> CANCELED Error Code

- Protocol.md
Love the changes in #197.
This PR is the missing bit.
> Unsigned is >= 0 by definition

- Protocol.md
Possible wording if we agree to allow Stream ID re-use. Discussion in https://github.com/ReactiveSocket/reactivesocket/issues/221
> support for Stream ID re-use

- Protocol.md
Seek to clarify Complete and Next flags as per https://github.com/ReactiveSocket/reactivesocket/issues/226#issuecomment-284755017
> clarify (C)omplete and (N)ext flags

- Protocol.md
Proposed wording in case we choose to make Metadata Length header optional.
See https://github.com/ReactiveSocket/reactivesocket/issues/228
> Proposal for optional metadata length header

- Protocol.md
> Clarify metadata length value

- Protocol.md
Came across these while reading through the protocol specification :grin:
> Fix couple of typos in Protocol.md

- Extensions/WellKnownMimeTypes.md
x-hessian & x-java-object are very important for Java applications.  cloudevents+json is very promising type for event processing and already used in different systems.  x.rsocket.data-encoding.v0  is for data encoding for every Payload.
> add types for hessian, java-object, cloudevents json and rsocket.data

- Extensions/Security/Authentication.md
- Extensions/Security/Basic.md
- Extensions/Security/Bearer.md
- Extensions/Security/Simple.md
- Extensions/Security/WellKnownAuthTypes.md
- Extensions/WellKnownMimeTypes.md
> Add Authentication Metadata Extension

- Extensions/Security/Simple.md
This PR clarifies the username length field for Simple Authentication type payload
> Clarify username length field

- Extensions/Routing.md
This PR provides minor clarification to the spec
> Clarifies Routing Metadata

- Protocol.md
> Protocol - frame length clarification.
